quick clean up
dgonzalez/visigoth pull request #2
Opened 2017-03-20 20:02 UTC by wzrdtales

As talked the transfer from dgonzalez/visigoth-old#2

not sure where it should be opened up on, its there in both places now:
https://github.com/rjrodger/visigoth/pull/3

2017-03-20 20:07 UTC, dgonzalez requested changes
Looks good. Just change the license and I will merge it. This is the correct repo.

2017-03-20 20:07 UTC, dgonzalez commented on examples/econ-refused/package.json
> +  "license": "ISC",
License should be MIT (as per base repo)

2017-03-20 20:07 UTC, dgonzalez commented on examples/econ-refused/package.json
> +  "license": "ISC",
Applies for all the other examples.

2017-03-20 21:43 UTC, wzrdtales commented on examples/econ-refused/package.json
> +  "license": "ISC",
Sure will Update this just quickly Cherry picked the old One

2017-03-21 07:27 UTC, wzrdtales commented
@dgonzalez Pushed the requested changes out. About the repo constellation. It is quite a struggle to open a PR in this constellation as you always end up by default in rjdoger ones. Is there a special reason for this structure?

2017-03-21 08:43 UTC, dgonzalez commented
No, repo will be transferred to my account. This is the right one. Thanks for your changes!

2017-03-21 08:43 UTC, merged